version: "3"
services:
  vaya:
    build:
      context: ./vaya
      dockerfile: Dockerfile
    container_name: vaya
    ports:
      - "9003:8080"
    volumes:
      - ./vaya:/app
      - ./vaya/node_modules:/app/node_modules
